import type { Metadata } from 'next';
import { Geist, Geist_Mono, Roboto } from 'next/font/google';

import ReactQueryClientProvider from './_components/ReactQueryClientProvider';
import MuiThemeProvider from './_components/SetUpMuiCacheProvider';
import ZustandHydration from './_components/ZustandHydration';
import GlobalStoreProvider from './_providers/GlobalStoreProvider';

import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryClientProvider>
      <html lang="en">
        <body
          className={`${roboto.variable} ${geistSans.variable} ${geistMono.variable}`}
        >
          <MuiThemeProvider>
            <GlobalStoreProvider>
              <ZustandHydration>{children}</ZustandHydration>
            </GlobalStoreProvider>
          </MuiThemeProvider>
        </body>
      </html>
    </ReactQueryClientProvider>
  );
}
