name: 🚀 Deploy FE

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Select an environment to deploy on'
        required: true
        default: 'dev'
        options:
          - dev
          - staging
          - prod

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  FIREBASE_SERVICE_ACCOUNT_KEY_JSON: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY_JSON }}
  FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build Vite app
        run: yarn build

      - name: Build and deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ env.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ env.FIREBASE_SERVICE_ACCOUNT_KEY_JSON }}
          channelId: live
          projectId: ${{ env.FIREBASE_PROJECT_ID }}
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
